export let categories = [
    "Animals", "Countries", "Capital Cities", "Girl Names", "Boy Names", 
    "Fruits", "Vegetables", "Colors", "Movies", "TV Shows", 
    "Superheroes", "Villains", "Brands", "Clothing Items", "Sports",
    "Musical Instruments", "Holidays", "Pizza Toppings", "Ice Cream Flavors", "Desserts",
    "Breakfast Foods", "Fast Food Chains", "Soft Drinks", "Video Games", "Board Games",
    "School Subjects", "Professions", "Body Parts", "Languages", "Flowers",
    "Insects", "Birds", "Sea Creatures", "Dog Breeds", "Cars",
    "Space/Planets", "Weather Words", "Tools", "Furniture", "Kitchen Appliances",
    "Stationery", "Hobby", "Disney Characters", "Cartoon Characters", "Famous Singers",
    "Actors", "Historical Figures", "Countries in Europe", "Countries in Asia", "US States",
    "Chemical Elements", "Math Terms", "Types of Fabric", "Jewelry", "Footwear",
    "Makeup Brands", "Tech Companies", "Apps on your Phone", "Social Media Platforms", "Websites",
    "Card Games", "Olympic Sports", "Winter Activities", "Summer Activities", "Things at a Beach",
    "Things in a Forest", "Things in a Hospital", "Things in a Circus", "Things in a Zoo", "Things in a Gym",
    "Things in an Office", "Things in a Bedroom", "Things in a Garage", "Things in a Suitcase", "Things in a Purse",
    "Street Names", "Cereal Brands", "Chocolate Bars", "Candy Brands", "Spices",
    "Condiments", "Sandwich Fillings", "Types of Pasta", "Types of Bread", "Cheeses",
    "In the Fridge", "Under the Bed", "Scary Things", "Yellow Things", "Liquid Things",
    "Found in a Library", "Found in a Museum", "Found in a Park", "Airport Items", "Wedding Items",
    "Baby Items", "Pet Supplies", "Cleaning Products", "Gardening Tools", "Camping Gear",
    "Musical Genres", "Book Titles", "Magazines", "Newspapers", "Movie Studios",
    "World Landmarks", "Mountains", "Rivers", "Oceans", "Types of Trees",
    "Precious Stones", "Constellations", "Zodiac Signs", "Units of Measure", "Currencies",
    "Languages of the World", "Dictators", "Monsters", "Mythical Creatures", "Aliens",
    "Robots", "Detectives", "Pirate Related", "Cowboy Related", "Space Travel",
    "Magic Tricks", "Circus Acts", "Fairground Rides", "Toys", "Souvenirs",
    "Postage Stamps", "Antiques", "Art Styles", "Dance Styles", "Poets",
    "Inventors", "Scientists", "Philosophers", "Explorers", "Kings and Queens",
    "British Words", "Slang Words", "Compound Words", "Palindromes", "Rhyming Words",
    "Things that are Hot", "Things that are Cold", "Things that are Soft", "Things that are Loud", "Things that Smell",
    "Fragile Items", "Heavy Items", "Square Things", "Round Things", "Sharp Things",
    "Sticky Things", "Electric Items", "Battery Operated", "Vintage Items", "Eco-friendly Items",
    "Luxury Brands", "Budget Brands", "Online Stores", "Department Stores", "Toy Stores",
    "Hardware Stores", "Pharmacy Items", "Hardware Items", "Automotive Parts", "Bicycle Parts",
    "Skateboard Brands", "Sneaker Models", "Fashion Designers", "Architects", "Painters",
    "Composers", "Opera Singers", "Broadway Musicals", "Classical Music", "Jazz Legends",
    "Rappers", "Pop Stars", "Rock Bands", "Indie Movies", "Action Movies",
    "Horror Movies", "Sci-Fi Movies", "Romantic Comedies", "Documentaries", "Reality TV",
    "Cooking Shows", "Game Shows", "News Anchors", "Youtubers", "Podcasts",
    "E-mail Providers", "Operating Systems", "Programming Languages", "Hardware Components", "Cloud Services",
    "AI Tools", "Cryptocurrencies", "NFT Projects", "Smart Home Devices", "Wearable Tech"
  ]
